# Generated by Django 5.1.1 on 2024-11-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='candidate',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='description',
            new_name='content',
        ),
    ]
