# Generated by Django 5.1.1 on 2024-11-19 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0002_alter_policy_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='campaign_slogan',
            new_name='slogan',
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='policy',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='policy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='candidate_app.candidate'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
