# Generated by Django 5.1.1 on 2024-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0003_rename_campaign_slogan_candidate_slogan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
