# Generated by Django 5.1.1 on 2024-11-18 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_app.candidate'),
        ),
    ]
